env:
    global:
        - PACKAGE="MarkdownTOC" # Package name
        - SUBLIME_TEXT_VERSION="3"
        # use UNITTESTING_TAG to specific tag of UnitTesting
        # - UNITTESTING_TAG="master"

# mutliple os matrix
# https://docs.travis-ci.com/user/multi-os/#Python-example-(unsupported-languages)
matrix:
    include:
        - os: linux
          services: xvfb
          language: python
          python: 3.7
        - os: osx
          language: generic


before_install:
    - curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/travis.sh
    # enable gui, see https://docs.travis-ci.com/user/gui-and-headless-browsers
    - if [ "$TRAVIS_OS_NAME" == "linux"  ]; then
            export DISPLAY=:99.0;
            sh -e /etc/init.d/xvfb start;
            sleep 3;
      fi

install:
    # bootstrap the testing environment
    - sh travis.sh bootstrap
    # install Package Control and package denepdencies
    # - sh travis.sh install_package_control

script:
    # run tests with test coverage report
    - sh travis.sh run_tests --coverage
    # testing syntax_test files
    # - sh travis.sh run_syntax_tests

after_success:
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
            brew update;
            brew install python3;
            pip3 install codecov;
      fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
            pip install codecov;
      fi
    - codecov -t e41883b8-547a-4728-a703-d8e1bbedfcf8

notifications:
    email: true
