environment:
    # The package name
    PACKAGE: "MarkdownTOC"
    SUBLIME_TEXT_VERSION : "3"

install:
    - ps: appveyor DownloadFile "https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/appveyor.ps1"
    - ps: .\appveyor.ps1 "bootstrap" -verbose
    # install Package Control
    # - ps: .\appveyor.ps1 "install_package_control" -verbose

build: off

test_script:

    # run tests with test coverage report
    - ps: .\appveyor.ps1 "run_tests" -coverage -verbose

on_finish:
    - "SET PYTHON=C:\\Python33"
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - pip install codecov
    - codecov